### ISSUE TITLE
Global settings

### ISSUE THREAD

**Issue by krstivoja** [KevinBatdorf/code-block-pro#172]
Can you please add global change for theme, header and footer. 

<3 Love the plugin by the way!

**Comment by KevinBatdorf** [comment]
Thanks. It's a difficult problem to solve I think but I'll work on that next.

**Comment by krstivoja** [comment]
You can create settings page under Admin > Tools where user can choose defaults. If you need any help I am glad to help.

**Comment by adriancs2** [comment]
As an alternative solution, you can modify some of the style of code block globally by adding additional CSS to the frontend.

You can use a plugin called [Simple Custom CSS and JS](https://wordpress.org/plugins/custom-css-js/).

Screenshot of using the plugin:
![code-block-border-radius](https://github.com/KevinBatdorf/code-block-pro/assets/646615/dc0c4c03-5964-413e-862b-00c29354e90f)

You can change the basic styling, for example:
```css
/* Modifying the Border Radius*/
.wp-block-kevinbatdorf-code-block-pro:not(.code-block-pro-editor) pre {
    border-radius: 10px !important;
}

/* Modifying the top and bottom margin */
.wp-block-kevinbatdorf-code-block-pro {
    margin-top: 25px; /* Top Margin */
    margin-bottom: 25px; /* Bottom Margin */
}

/* Use any font resource you prefer, example: import Google Font */
@import url('https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@400;500;700&display=swap');

/* Change font, font-size, line-height, font-weight */
.wp-block-kevinbatdorf-code-block-pro pre code {
    font-family: "Roboto Mono", monospace !important;	
    line-height: 135% !important;
    font-size: 13px !important;
    font-weight: 400 !important;
}

/* Change the cursor highlight background color */
.wp-block-kevinbatdorf-code-block-pro pre span::selection {
    background-color: #336ecc; /* Cursor highlight background color */
    color: white; /* Cursor highlight text color */
}
```

**Comment by adriancs2** [comment]
Here is how I identify the class selector block for specific elements:
![identifying the code block](https://github.com/KevinBatdorf/code-block-pro/assets/646615/d9d0cd8b-3ec8-4efe-af17-80dac144025f)

**Comment by adriancs2** [comment]
For the `border-radius: 10px !important;`, at the browser developer's mode "elements" tab, I manually insert the style into the element's attribute to find out the exact block that has the direct influence for the style. With this, I am able to find the correct selector.

![find-element](https://github.com/KevinBatdorf/code-block-pro/assets/646615/57f1a452-6aee-44d4-9b9f-d10fc243e4bb)

**Comment by adriancs2** [comment]
I found that, you can even adjust the maximum code block height and change the scroll bar style. But the scroll bar style below does not apply in Firefox:

```css
.wp-block-kevinbatdorf-code-block-pro pre {
	max-height: 300px;
}

.wp-block-kevinbatdorf-code-block-pro pre::-webkit-scrollbar {
    width: 10px;
    height: 10px;
}

.wp-block-kevinbatdorf-code-block-pro pre::-webkit-scrollbar-track {
    background: #979797;
}

.wp-block-kevinbatdorf-code-block-pro pre::-webkit-scrollbar-thumb {
    background: #7a7a7a;
    border-radius: 10px;
}

.wp-block-kevinbatdorf-code-block-pro pre::-webkit-scrollbar-thumb:hover {
        background: #656565;
    }

    .wp-block-kevinbatdorf-code-block-pro pre::-webkit-scrollbar-thumb:active {
        background: #383838;
    }
```
