### ISSUE TITLE
How to make copy icon always visible?

### ISSUE THREAD

**Issue by Mord3c4i** [KevinBatdorf/code-block-pro#178]
How can I remove the vanishing hover effect on the copy code icon?

**Comment by KevinBatdorf** [comment]
You can add some CSS to your site like this:

```css
span.code-block-pro-copy-button {
    opacity: 1!important;
}
```
