### ISSUE TITLE
Issue with margins and rounded corners

### ISSUE THREAD

**Issue by vandadnp** [KevinBatdorf/code-block-pro#187]
Hi Kevin

Thank you for Code Block Pro. I am really enjoying it.

I have two issues with it right now which I thought to bring up with you.

Issue 1 is that when we have the macOS-style code-block, the corners are not rounded. All macOS windows have rounded corners so this is a cosmetic issue. To make it look truly macOS style, we need to have all code-blocks of this type have rounded corners:

Issue 2 is that code blocks are missing margins before the next paragraph starts. The paragraph directly following a code-style is too close to the bottom.

<img width="497" alt="Screenshot 2023-05-05 at 06 49 39" src="https://user-images.githubusercontent.com/759524/236379900-0949d971-c21f-47ef-8a61-9d1a9dd03ea3.png">

Thanks in advance

**Comment by KevinBatdorf** [comment]
I've left the block styling outside of the block untouched as that's generally the responsibility of the theme to determine spacing for _all_ blocks. WordPress I think will be adding something to adjust this in 6.3 though. I may add something anyway since it comes up enough and might not be practical to rely on themes to work properly. For now though you can add some global CSS:

```css
[class*='-code-block-pro'] {
    border-radius: 0.75rem !important;
    overflow: hidden !important;
    margin-bottom: 1rem !important;
}
```
