### ISSUE TITLE
Add simple controls for top/bottom margins, and border-radius

### ISSUE THREAD

**Issue by KevinBatdorf** [KevinBatdorf/code-block-pro#191]
This is really more of a theme or WP core thing, I think, but while WP is catching up I can add a few common styling tools tot he editor.

**Comment by adriancs2** [comment]
Here's in a alternative solution:

I am able to edit the top.bottom margin and border-radius with the help of a plugin call [Simple Custom CSS and JS](https://wordpress.org/plugins/custom-css-js/)

With the help of the plugin, insert the following CSS to the frontend:
```css
.wp-block-kevinbatdorf-code-block-pro {
    margin-top: 25px; /* Top Margin */
    margin-bottom: 25px; /* Bottom Margin */
}

.wp-block-kevinbatdorf-code-block-pro:not(.code-block-pro-editor) pre {
	/* Border Radius of the code block */
    border-radius: 10px !important;
}
```
![code-block-border-radius](https://github.com/KevinBatdorf/code-block-pro/assets/646615/dc0c4c03-5964-413e-862b-00c29354e90f)
