### ISSUE TITLE
Line Line break for XML code

### ISSUE THREAD

**Issue by pglu** [KevinBatdorf/code-block-pro#221]
I want to publish a XML code window with your plugin. In the backend the code is shown with line breaks, which correspond to the width of the box In addition, I have limited the height of the box to 150px, which is why a vertical scrollbar is shown. This is exactly how I want it. But in the frontend, the XML code is displayed without line breaks, with a horizontal scrollbar. Is it possible to adjust this? See here: https://pglu.ch/test-beitrag/

**Comment by KevinBatdorf** [comment]
It's actually a bit complicated to implement this on the front end and have it working with all features like line highlighting, blurs, etc. I'll revisit it at some point though.

If you want, you can do this with CSS now. Just add the following:

```css
div[class*='code-block-pro']:not(.x) pre {
    padding-right: 12px !important;
    max-height: 150px !important;
}
div[class*='code-block-pro']:not(.x) pre code {
    white-space: normal !important;
}
```

If you don't want the word wrap on every block, you can add a class (ex `custom-class`) on the block and use this

```css
div[class*='code-block-pro'].custom-class pre {
    padding-right: 12px !important;
    max-height: 150px !important;
}
div[class*='code-block-pro'].custom-class pre code {
    white-space: normal !important;
}
```

![Screen Shot 2023-07-24 at 12 51 36 PM](https://github.com/KevinBatdorf/code-block-pro/assets/1478421/ee96fb80-948b-473d-893c-b82ea8c6f668)
