### ISSUE TITLE
Keep Line Numbers Fixed During Horizontal Scrolling

### ISSUE THREAD

**Issue by vishnumaiea** [KevinBatdorf/code-block-pro#250]
When the line numbers are enabled, the current behavior is also to scroll them along with the code when scrolled horizontally.

![image](https://github.com/KevinBatdorf/code-block-pro/assets/10383395/27484bb4-2162-4e52-af42-091f81765337)
Image 1 - Before scrolling

![image](https://github.com/KevinBatdorf/code-block-pro/assets/10383395/d0e3542c-3b92-4ebc-958f-0461d923edea)
Image 2 - After horizontal scrolling

But this is not the behavior of any text editors including VS Code. Instead, the line numbers remain stationary during horizontal scrolling. When a line is long, it makes it difficult for the user to see which line is which when scrolled.

**Comment by worldsdream** [comment]
This option would be great to have. So we as admins, can choose which option we like (with or without line numbers fixed).

**Comment by KevinBatdorf** [comment]
It looks like it will require me to add extra JS to handle line highlighting and I want to keep that JS code as light as possible. 

I'm still exploring some options though, and might land on adding a module to include some CSS snippets, with some "common recipes" that let you add in something for this.

**Comment by KevinBatdorf** [comment]
btw there is some CSS here you could try. If anyone wants to share a URL I can customize it a bit more based on their theme, etc

```css
div[class*='code-block-pro']:not(.x) pre {
    padding-right: 12px !important;
}
div[class*='code-block-pro']:not(.x) pre code {
    white-space: normal !important;
}
```

**Comment by dcooney** [comment]
The solution above appears to remove line indentation (tabs/spaces etc).

Before: 

<img width="777" alt="image" src="https://github.com/user-attachments/assets/63c58f7c-d01a-499a-81cf-532d64207908">

In my testing, the following CSS works by appearing `white-space` rules to the `span.line` elements.

```css
div[class*='code-block-pro']:not(.x) pre span.line {
	white-space: pre-wrap;
}
```
After:
<img width="774" alt="image" src="https://github.com/user-attachments/assets/c63333d1-4aac-4ff0-80c6-b59753d0110f">
