### ISSUE TITLE
How to avoid this white space problem using code block pro ?

### ISSUE THREAD

**Issue by rodrigomc2000** [KevinBatdorf/code-block-pro#262]
Hello everyone :)

My JSON example have a large link:

https://pps.whatsapp.net/v/t61.24694-24/323970788_1137981286878828_1882391295127733628_n.jpg?stp=dst-jpg_s96x96&ccb=11-4&oh=01_AdRIhDQmoDnnUAXJdVlRp9eCiVzLdQK5ogchK1GhiSLnAw&oe=6534E077&_nc_sid=000000&_nc_cat=101

And it's causing a horizontal scroll in front end:

![hXXmpSyzX5](https://github.com/KevinBatdorf/code-block-pro/assets/48796986/205d2082-4070-47d0-b729-8efae106a389)

But in page builder show correct:

![u6qeD2gWUm](https://github.com/KevinBatdorf/code-block-pro/assets/48796986/aea06b8e-2bae-4de5-bf28-34b2bacf4fec)

How to fix this?

Thanks

**Comment by KevinBatdorf** [comment]
It's designed to scroll like that intentionally. I'm going to look into adding it as an option but its a bit complicated to get it working with all the other features (like line highlighting, for example)

If you wants to share a link to your site I can look at it. You can also try css like this:

```css
div[class*='code-block-pro']:not(.x) pre {
    padding-right: 12px !important;
}
div[class*='code-block-pro']:not(.x) pre code {
    white-space: normal !important;
}
```
