### ISSUE TITLE
Add word wrap in print styles

### ISSUE THREAD

**Issue by KevinBatdorf** [KevinBatdorf/code-block-pro#312]
The cod egets cut off. Word wrap and line highlighting dont play nice together today but with print it will work.

```css
@media print {
  .wp-block-kevinbatdorf-code-block-pro:not(#x) pre code {
    text-wrap: wrap !important;
  }
  .wp-block-kevinbatdorf-code-block-pro:not(#x) .line {
    min-width: 0 !important;
  }
}
```
