### ISSUE TITLE
Code block has no bottom margin

### ISSUE THREAD

**Issue by KevinBatdorf** [KevinBatdorf/code-block-pro#314]
So non-block themes will add `<pre>` margin bottom values that I should respect somehow. I zero these out since block themes will add spacing between blocks, so the `<pre>` bottom margins there will add double spacing. 

I'm not sure how to yet how to solve this, as I want to force override margins on block themes, but allow them on non-block themes.

For now, if you end up here, you can add this CSS (update the margin-bottom value to your preference)

```css
div[class*='code-block-pro']:not(.x) pre {
    margin-bottom: 1rem !important;
}
```

related: https://wordpress.org/support/topic/after-code-block-paragraph-is-combined-without-any-space/
