### ISSUE TITLE
How about a global font? or global block css properties?

### ISSUE THREAD

**Issue by adriancs2** [KevinBatdorf/code-block-pro#88]
Hi, thanks for the awesome plugin. I love it very much :)

About the font being used in the code block, by default, it uses the font defined by the wordpress's theme. But I do not like the font. I know that code-block-pro does provide built-in font options to choose for each block.

I have an idea, a feature suggestion. How about provide a global settings for code-block-pro to apply some default CSS properties? for example:
```
padding
margin
font-family
font-size
font-weight
line-height
```
What I'm currently doing is by using another plugin: Custom CSS and JS
https://wordpress.org/plugins/custom-css-js/

that loads my defined CSS in the last section of HTML header
![custom css3](https://user-images.githubusercontent.com/646615/210045934-31924dd6-1143-4116-be6c-04c63924d4f5.png)

**Comment by adriancs2** [comment]
Another possible feature is importing Google Fonts of Monospace fonts.
which will be imported like this at the HTML doc header:
```css
@import url('https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@300&display=swap');
.block {
    font-family: "Roboto Mono", monospace;
}
```
